---
- name: Deploy app and create service in k8s
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Deploy deployment and service in k8s cluster
      shell: kubectl apply -f deployment_service.yml
